trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet workload restore
  displayName: 'Restore .NET workloads (wasm-tools)'

- script: dotnet publish ComicOpenSilver.Browser/ComicOpenSilver.Browser.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Publish Browser project'

- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web Apps'
  inputs:
    app_location: '$(Build.ArtifactStagingDirectory)/publish/wwwroot'
    output_location: ''
    azure_static_web_apps_api_token: $(deployment_token)
    skip_app_build: true
